version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "/code/startup.sh"
    volumes:
      - .:/code
    ports:
      - "4367:8000"
    depends_on:
      - db

volumes:
  postgres_data:
