# Generated by Django 5.0 on 2023-12-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info_one',
            options={'verbose_name': 'Info1', 'verbose_name_plural': 'Info1'},
        ),
        migrations.AlterModelOptions(
            name='info_two',
            options={'verbose_name': 'Info2', 'verbose_name_plural': 'Info2'},
        ),
        migrations.AlterField(
            model_name='info_one',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info_two',
            name='info',
            field=models.TextField(),
        ),
    ]
