# Generated by Django 5.0 on 2023-12-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
